import { expect, test } from '@playwright/test'

test('microscene 7.3 maps each arm tab to one complete image and plays muted video', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Mulai: Sistem Reproduksi/ }).click()
  await page.getByRole('button', { name: /Lanjut: Otot & Tulang/ }).click()
  const scene = page.getByTestId('muscle-bone-scene')
  const arm = page.getByTestId('movement-arm')
  await expect(arm).toHaveAttribute('src', /01_lengan_penuh_lurus/)
  await page.waitForTimeout(700)
  await page.screenshot({ path: `e2e/screenshots/${testInfo.project.name}-sistem-organ-3-7-3-straight.png` })
  await page.getByRole('tab', { name: 'Lengan Menekuk' }).click()
  await expect(arm).toHaveAttribute('src', /02_lengan_penuh_tertekuk_bisep/)
  await page.screenshot({ path: `e2e/screenshots/${testInfo.project.name}-sistem-organ-3-7-3-flexed.png` })
  await page.getByTestId('movement-play').click()
  const video = page.getByTestId('movement-video')
  await expect(video).toHaveAttribute('src', /animation\.mp4/)
  await expect(video).toHaveJSProperty('muted', true)
  await expect(scene).toHaveAttribute('data-animation', 'playing')
  await page.waitForTimeout(1_000)
  await page.screenshot({ path: `e2e/screenshots/${testInfo.project.name}-sistem-organ-3-7-3-animation.png` })
  await video.evaluate((node) => node.dispatchEvent(new Event('ended')))
  await expect(arm).toHaveAttribute('src', /02_lengan_penuh_tertekuk_bisep/)
})
