import { expect, test } from '@playwright/test'

test('microscene 6.1 through 6.5 stage their bubble transitions in and out', async ({ page }, testInfo) => {
  await page.goto('/')

  const first = page.getByTestId('sistem-organ-2-scene')
  await expect(first).toBeVisible()
  await expect(first).toHaveAttribute('data-exiting', 'false')
  await expect(page.locator('.sistem-organ-2__header')).toHaveCSS('animation-name', 'sistem-organ-2-header-in')
  await page.waitForTimeout(170)
  await page.screenshot({ path: `e2e/screenshots/${testInfo.project.name}-sistem-organ-2-transition-6-1-in-mid.png` })
  await page.waitForTimeout(530)
  await expect(page.locator('.sistem-organ-2__list')).toHaveCSS('opacity', '1')
  await expect(page.locator('.sistem-organ-2__anatomy')).toHaveCSS('opacity', '1')
  await expect(page.locator('.sistem-organ-2__info')).toHaveCSS('opacity', '1')
  await page.screenshot({ path: `e2e/screenshots/${testInfo.project.name}-sistem-organ-2-transition-6-1-in.png` })

  await page.getByTestId('sistem-organ-2-next-button').click()
  await expect(first).toHaveAttribute('data-exiting', 'true')
  await expect(page.locator('.sistem-organ-2__header')).toHaveCSS('animation-name', 'sistem-organ-2-header-out')
  await page.waitForTimeout(220)
  await page.screenshot({ path: `e2e/screenshots/${testInfo.project.name}-sistem-organ-2-transition-6-1-out-mid.png` })

  const second = page.getByTestId('digestion-journey-scene')
  await expect(second).toBeVisible({ timeout: 1_500 })
  await expect(second).toHaveAttribute('data-exiting', 'false')
  await expect(page.locator('.digestion-journey__header')).toHaveCSS('animation-name', 'digestion-header-in')
  await page.waitForTimeout(170)
  await page.screenshot({ path: `e2e/screenshots/${testInfo.project.name}-sistem-organ-2-transition-6-2-in-mid.png` })
  await page.waitForTimeout(530)
  await expect(page.locator('.digestion-journey__list')).toHaveCSS('opacity', '1')
  await expect(page.locator('.digestion-journey__anatomy')).toHaveCSS('opacity', '1')
  await expect(page.locator('.digestion-journey__info')).toHaveCSS('opacity', '1')
  await page.getByRole('button', { name: /Lanjut: Sistem Persarafan/ }).click()
  await expect(second).toHaveAttribute('data-exiting', 'true')
  await expect(page.locator('.digestion-journey__header')).toHaveCSS('animation-name', 'digestion-header-out')
  await page.waitForTimeout(220)
  await page.screenshot({ path: `e2e/screenshots/${testInfo.project.name}-sistem-organ-2-transition-6-2-out-mid.png` })

  const third = page.getByTestId('nerve-impulse-scene')
  await expect(third).toBeVisible({ timeout: 1_500 })
  await expect(third).toHaveAttribute('data-exiting', 'false')
  await expect(page.locator('.nerve-impulse__header')).toHaveCSS('animation-name', 'nerve-scene-header-in')
  await page.waitForTimeout(170)
  await page.screenshot({ path: `e2e/screenshots/${testInfo.project.name}-sistem-organ-2-transition-6-3-in-mid.png` })
  await page.waitForTimeout(530)
  await expect(page.locator('.nerve-impulse__list')).toHaveCSS('opacity', '1')
  await expect(page.locator('.nerve-impulse__anatomy')).toHaveCSS('opacity', '1')
  await expect(page.locator('.nerve-impulse__info')).toHaveCSS('opacity', '1')
  await page.getByRole('button', { name: /Lanjut: Sistem Perkemihan/ }).click()
  await expect(third).toHaveAttribute('data-exiting', 'true')
  await expect(page.locator('.nerve-impulse__header')).toHaveCSS('animation-name', 'nerve-scene-header-out')
  await page.waitForTimeout(220)
  await page.screenshot({ path: `e2e/screenshots/${testInfo.project.name}-sistem-organ-2-transition-6-3-out-mid.png` })

  const fourth = page.getByTestId('urinary-journey-scene')
  await expect(fourth).toBeVisible({ timeout: 1_500 })
  await expect(fourth).toHaveAttribute('data-exiting', 'false')
  await expect(page.locator('.urinary-journey__header')).toHaveCSS('animation-name', 'urinary-header-in')
  await page.waitForTimeout(170)
  await page.screenshot({ path: `e2e/screenshots/${testInfo.project.name}-sistem-organ-2-transition-6-4-in-mid.png` })
  await page.waitForTimeout(530)
  await expect(page.locator('.urinary-journey__list')).toHaveCSS('opacity', '1')
  await expect(page.locator('.urinary-journey__anatomy')).toHaveCSS('opacity', '1')
  await expect(page.locator('.urinary-journey__info')).toHaveCSS('opacity', '1')
  await page.getByRole('button', { name: /Lanjut: Sistem Reproduksi/ }).click()
  await expect(fourth).toHaveAttribute('data-exiting', 'true')
  await expect(page.locator('.urinary-journey__header')).toHaveCSS('animation-name', 'urinary-header-out')
  await page.waitForTimeout(220)
  await page.screenshot({ path: `e2e/screenshots/${testInfo.project.name}-sistem-organ-2-transition-6-4-out-mid.png` })

  const fifth = page.getByTestId('three-systems-challenge-scene')
  await expect(fifth).toBeVisible({ timeout: 1_500 })
  await expect(fifth).toHaveAttribute('data-exiting', 'false')
  await expect(page.locator('.three-systems-challenge__header')).toHaveCSS('animation-name', 'challenge-header-in')
  await page.waitForTimeout(170)
  await page.screenshot({ path: `e2e/screenshots/${testInfo.project.name}-sistem-organ-2-transition-6-5-in-mid.png` })
  await page.waitForTimeout(530)
  await expect(page.locator('.three-systems-challenge__choices')).toHaveCSS('opacity', '1')
  await expect(page.locator('.three-systems-challenge__workspace')).toHaveCSS('opacity', '1')
  await expect(page.locator('.three-systems-challenge__tips')).toHaveCSS('opacity', '1')
  await page.getByRole('button', { name: 'Sebelumnya', exact: true }).click()
  await expect(fifth).toHaveAttribute('data-exiting', 'true')
  await expect(page.locator('.three-systems-challenge__header')).toHaveCSS('animation-name', 'challenge-header-out')
  await page.waitForTimeout(220)
  await page.screenshot({ path: `e2e/screenshots/${testInfo.project.name}-sistem-organ-2-transition-6-5-out-mid.png` })
})
