import { useState, type CSSProperties } from 'react'
import { useGlobalAudio } from '../../audio/GlobalAudio'
import { ArrowLeft, ArrowRight, ChevronRight, Lightbulb, MapPin, Settings } from 'lucide-react'
import backgroundArt from '../../assets/02_scene/07_sistem_organ_3/backgrounds/1.png'
import femaleSystemArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/01_sistem_reproduksi_wanita_utuh.png'
import cervixAArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/02_serviks_potongan_A.png'
import cervixBArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/03_serviks_potongan_B.png'
import tubeOvaryArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/04_tuba_falopi_ovarium.png'
import tubeAArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/05_tuba_falopi_A.png'
import tubeBArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/06_tuba_falopi_B.png'
import cervixCArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/07_serviks_potongan_C.png'
import ovaryArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/08_ovarium.png'
import ovarySectionArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/09_ovarium_potongan_melintang.png'
import tubeCurveArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/10_tuba_falopi_lengkung.png'
import maleSystemArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/11_sistem_reproduksi_pria_utuh.png'
import vesicleAArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/13_vesikula_seminalis_A.png'
import vesicleBArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/14_vesikula_seminalis_B.png'
import prostateArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/15_kelenjar_prostat.png'
import testisAArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/16_testis_A.png'
import testisBArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/17_testis_B.png'
import vasAArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/18_vas_deferens_A.png'
import vasBArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/19_vas_deferens_B.png'
import epididymisAArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/20_epididimis_A.png'
import epididymisBArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/21_epididimis_B.png'
import urethraPenisArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.2/22_uretra_penis.png'
import bookArt from '../../assets/02_scene/07_sistem_organ_3/micro_scenes/7.1/08_icon_buku_biru.png'
import bgmOffArt from '../../assets/01_reusable/buttons/btn_bgm_off.png'
import bgmOnArt from '../../assets/01_reusable/buttons/btn_bgm_on.png'
import homeArt from '../../assets/01_reusable/buttons/btn_home.png'
import { useSceneExitTransition } from '../../hooks/useSceneExitTransition'
import { useStageCoverScale } from '../../hooks/useStageCoverScale'
import './ReproductionSystemScene.css'

type Mode = 'female' | 'male'
type Part = { id: string; label: string; cardArts: string[]; infoArt: string; title: string; description: string; location: string; function: string; system: string; fact: string }
type Callout = { text: string; x: number; y: number; lineX: number; lineY: number; lineLength: number; lineAngle: number; active?: boolean }
const female = (id: string, label: string, cardArts: string[], infoArt: string, description: string, location: string, fn: string, system: string, fact: string): Part => ({ id, label, cardArts, infoArt, title: label, description, location, function: fn, system, fact })
const male = female
const FEMALE: Part[] = [
  female('ovarium', 'Ovarium', [ovaryArt], ovarySectionArt, 'Organ kecil yang menghasilkan sel telur dan hormon reproduksi.', 'Terletak di sisi kanan dan kiri rahim.', 'Menghasilkan sel telur serta hormon estrogen dan progesteron.', 'Melepaskan sel telur ke tuba falopi untuk kemungkinan pembuahan.', 'Perempuan biasanya memiliki dua ovarium.'),
  female('tuba', 'Tuba Falopi', [tubeAArt, tubeBArt], tubeCurveArt, 'Saluran yang menghubungkan ovarium dengan rahim.', 'Terletak di antara ovarium dan rahim.', 'Menyalurkan sel telur menuju rahim dan menjadi tempat pembuahan.', 'Menghubungkan ovarium dengan rahim.', 'Pembuahan biasanya terjadi di tuba falopi.'),
  female('uterus', 'Uterus (Rahim)', [tubeOvaryArt], femaleSystemArt, 'Organ berongga yang menjadi tempat berkembangnya embrio dan janin selama kehamilan.', 'Terletak di rongga panggul, di antara kandung kemih dan rektum.', 'Sebagai tempat implantasi dan perkembangan embrio hingga menjadi janin.', 'Merupakan organ utama yang terhubung dengan tuba falopi di bagian atas dan serviks di bagian bawah.', 'Dinding uterus dapat menebal setiap bulan untuk mempersiapkan kehamilan.'),
  female('serviks', 'Serviks', [cervixAArt], cervixBArt, 'Bagian bawah rahim yang menghubungkan rahim dengan vagina.', 'Terletak di bagian bawah uterus.', 'Menjadi jalur antara uterus dan vagina.', 'Mengatur akses menuju rahim.', 'Serviks dapat membuka saat persalinan.'),
  female('vagina', 'Vagina', [cervixCArt], cervixCArt, 'Saluran elastis yang menghubungkan serviks dengan bagian luar tubuh.', 'Terletak di bawah serviks.', 'Menjadi jalan lahir dan saluran menstruasi.', 'Berhubungan langsung dengan serviks.', 'Vagina memiliki jaringan yang elastis.'),
]
const MALE: Part[] = [
  male('testis', 'Testis', [testisAArt, testisBArt], testisAArt, 'Organ yang menghasilkan sperma dan hormon testosteron.', 'Terletak di dalam skrotum.', 'Menghasilkan sperma dan hormon testosteron.', 'Memulai pembentukan sel reproduksi pria.', 'Testis bekerja paling baik pada suhu sedikit lebih rendah dari tubuh.'),
  male('epididimis', 'Epididimis', [epididymisAArt, epididymisBArt], epididymisAArt, 'Saluran tempat sperma matang dan disimpan sementara.', 'Menempel pada bagian atas dan belakang testis.', 'Menyimpan serta mematangkan sperma.', 'Menghubungkan testis dengan vas deferens.', 'Sperma membutuhkan waktu untuk matang di epididimis.'),
  male('vas', 'Vas Deferens', [vasAArt, vasBArt], vasAArt, 'Saluran yang membawa sperma dari epididimis.', 'Membentang dari epididimis menuju uretra.', 'Menyalurkan sperma saat ejakulasi.', 'Menghubungkan epididimis dengan uretra.', 'Vas deferens adalah saluran berotot.'),
  male('prostat', 'Kelenjar Prostat', [prostateArt], prostateArt, 'Kelenjar yang menghasilkan cairan sebagai bagian dari semen.', 'Terletak di bawah kandung kemih dan mengelilingi bagian awal uretra.', 'Menghasilkan cairan prostat yang membantu melindungi dan menutrisi sperma.', 'Cairan yang dihasilkan bercampur dengan sperma dari testis dan cairan dari vesikula seminalis untuk membentuk semen.', 'Cairan prostat bersifat sedikit basa, yang membantu melindungi sperma dari lingkungan asam di saluran reproduksi perempuan.'),
  male('vesikula', 'Vesikula Seminalis', [vesicleAArt, vesicleBArt], vesicleAArt, 'Kelenjar yang menghasilkan cairan kaya nutrisi untuk sperma.', 'Terletak di belakang kandung kemih.', 'Menghasilkan sebagian besar cairan semen.', 'Bekerja bersama prostat saat membentuk semen.', 'Cairannya mengandung nutrisi untuk sperma.'),
  male('uretra', 'Uretra', [urethraPenisArt], urethraPenisArt, 'Saluran yang membawa urine dan semen keluar dari tubuh.', 'Melewati prostat dan penis.', 'Menjadi saluran keluarnya urine atau semen.', 'Merupakan bagian dari sistem kemih dan reproduksi.', 'Urine dan semen tidak keluar bersamaan.'),
  male('penis', 'Penis', [urethraPenisArt], urethraPenisArt, 'Organ luar sistem reproduksi laki-laki.', 'Terletak di bagian luar tubuh.', 'Menyalurkan semen keluar dari tubuh.', 'Memuat bagian akhir uretra.', 'Penis juga berperan dalam sistem kemih.'),
]
const FEMALE_CALLOUTS: Callout[] = [
  { text: 'Tuba Falopi', x: 4, y: 30, lineX: 58, lineY: 29, lineLength: 58, lineAngle: 75 }, { text: 'Tuba Falopi', x: 500, y: 30, lineX: 44, lineY: 29, lineLength: 58, lineAngle: 105 }, { text: 'Uterus (Rahim)', x: 254, y: 69, lineX: 50, lineY: 34, lineLength: 115, lineAngle: 90, active: true }, { text: 'Ovarium', x: 5, y: 339, lineX: 93, lineY: 17, lineLength: 110, lineAngle: -70 }, { text: 'Ovarium', x: 500, y: 339, lineX: 10, lineY: 17, lineLength: 110, lineAngle: -110 }, { text: 'Serviks', x: 317, y: 408, lineX: 2, lineY: 17, lineLength: 78, lineAngle: -160 }, { text: 'Vagina', x: 317, y: 494, lineX: 2, lineY: 17, lineLength: 78, lineAngle: -160 },
]
const MALE_CALLOUTS: Callout[] = [
  { text: 'Kandung Kemih', x: 236, y: 14, lineX: 50, lineY: 32, lineLength: 58, lineAngle: 90 }, { text: 'Vas Deferens', x: 2, y: 118, lineX: 107, lineY: 17, lineLength: 44, lineAngle: 7 }, { text: 'Vesikula\nSeminalis', x: 501, y: 171, lineX: 6, lineY: 31, lineLength: 55, lineAngle: 170 }, { text: 'Kelenjar Prostat', x: 405, y: 264, lineX: 6, lineY: 18, lineLength: 66, lineAngle: 180, active: true }, { text: 'Epididimis', x: 2, y: 360, lineX: 105, lineY: 17, lineLength: 62, lineAngle: -27 }, { text: 'Uretra', x: 399, y: 405, lineX: 4, lineY: 17, lineLength: 77, lineAngle: -167 }, { text: 'Testis', x: 39, y: 460, lineX: 78, lineY: 17, lineLength: 69, lineAngle: -32 }, { text: 'Penis', x: 399, y: 524, lineX: 4, lineY: 17, lineLength: 70, lineAngle: 180 },
]
type Props = { onBackToHome?: () => void; onBack?: () => void; onComplete?: () => void }
export function ReproductionSystemScene({ onBackToHome, onBack, onComplete }: Props) {
  const scale = useStageCoverScale(1920, 1080, 1860, 1046); const [mode, setMode] = useState<Mode>('female'); const [selected, setSelected] = useState('uterus'); const { audioOn, toggleAudio } = useGlobalAudio(); const { isExiting, exitTo } = useSceneExitTransition(); const parts = mode === 'female' ? FEMALE : MALE; const active = parts.find((part) => part.id === selected) ?? parts[0]; const callouts = mode === 'female' ? FEMALE_CALLOUTS : MALE_CALLOUTS; const style = { '--stage-scale': scale } as CSSProperties
  const changeMode = (next: Mode) => { setMode(next); setSelected(next === 'female' ? 'uterus' : 'prostat') }
  return <main className={`reproduction-system reproduction-system--${mode}`} data-testid="reproduction-system-scene" data-microscene="7.2" data-mode={mode} data-selected={active.id} data-exiting={isExiting} style={style} aria-labelledby="reproduction-heading"><style>{'.reproduction-system--male .reproduction-system__info p{font-size:14px;line-height:1.22}.reproduction-system--male .reproduction-system__info h3{font-size:19px}'}</style><svg width="0" height="0" aria-hidden="true"><filter id="reproduction-black-key" colorInterpolationFilters="sRGB"><feColorMatrix type="matrix" values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 .333 .333 .333 0 0" /><feComponentTransfer><feFuncA type="linear" slope="6" intercept="-.03" /></feComponentTransfer></filter></svg><div className="reproduction-system__stage">
    <img className="reproduction-system__background" src={backgroundArt} alt="" /><button className="reproduction-system__icon reproduction-system__home" type="button" aria-label="Kembali ke Beranda" onClick={() => exitTo(onBackToHome)}><img src={homeArt} alt="" /></button><button className="reproduction-system__icon reproduction-system__audio" type="button" aria-label={audioOn ? 'Matikan musik latar' : 'Aktifkan musik latar'} aria-pressed={audioOn} onClick={() => toggleAudio()}><img src={audioOn ? bgmOnArt : bgmOffArt} alt="" /></button>
    <header className="reproduction-system__header"><p>Materi 4 - Sistem Organ Tubuh (2/5)</p><h1 id="reproduction-heading">Kenali Sistem Reproduksi</h1><span>Kenali organ utama sistem reproduksi dan pahami fungsi dasarnya dalam tubuh manusia.</span></header><div className="reproduction-system__tabs" role="tablist" aria-label="Pilih sistem reproduksi"><button role="tab" aria-selected={mode === 'female'} type="button" onClick={() => changeMode('female')}><b>♀</b>Sistem Reproduksi Perempuan</button><button role="tab" aria-selected={mode === 'male'} type="button" onClick={() => changeMode('male')}><b>♂</b>Sistem Reproduksi Laki-laki</button></div>
    <aside className="reproduction-system__list" aria-label="Pilih bagian organ"><h2><span>♧</span>Pilih Bagian</h2>{parts.map((part) => <button key={part.id} type="button" className="reproduction-system__card" data-testid={`reproduction-selector-${part.id}`} data-selected={part.id === active.id} aria-pressed={part.id === active.id} onClick={() => setSelected(part.id)}><span className="reproduction-system__card-art">{part.cardArts.map((art) => <img key={art} src={art} alt="" />)}</span><strong>{part.label}</strong><ChevronRight aria-hidden="true" /></button>)}</aside>
    <section className="reproduction-system__diagram" aria-label={`Diagram ${mode === 'female' ? 'perempuan' : 'laki-laki'}`}><img className="reproduction-system__organ" src={mode === 'female' ? femaleSystemArt : maleSystemArt} alt={`Ilustrasi sistem reproduksi ${mode === 'female' ? 'perempuan' : 'laki-laki'}`} style={{ filter: 'url(#reproduction-black-key)' }} />{callouts.map((callout) => <span key={`${callout.text}-${callout.x}`} className={`reproduction-system__callout${callout.active ? ' reproduction-system__callout--active' : ''}`} style={{ left: callout.x, top: callout.y } as CSSProperties}>{callout.text.split('\n').map((line) => <span key={line}>{line}</span>)}<i style={{ left: callout.lineX, top: callout.lineY, width: callout.lineLength, transform: `rotate(${callout.lineAngle}deg)` } as CSSProperties}><em /></i></span>)}</section>
    <aside className="reproduction-system__info" data-testid="reproduction-information" aria-live="polite"><header><span className="reproduction-system__info-art"><img src={active.infoArt} alt="" /></span><div><h2>{active.title}</h2><p>{active.description}</p></div></header><section><MapPin aria-hidden="true" /><div><h3>Lokasi</h3><p>{active.location}</p></div></section><section><Settings aria-hidden="true" /><div><h3>Fungsi Utama</h3><p>{active.function}</p></div></section><section><img src={bookArt} alt="" /><div><h3>Dalam Sistem Reproduksi</h3><p>{active.system}</p></div></section><footer><Lightbulb aria-hidden="true" /><div><h3>Tahukah Kamu?</h3><p>{active.fact}</p></div></footer></aside><button className="reproduction-system__bottom-back" type="button" onClick={() => exitTo(onBack)}><ArrowLeft aria-hidden="true" />Sebelumnya</button><button className="reproduction-system__next" type="button" onClick={() => exitTo(onComplete)}>Lanjut: Otot &amp; Tulang<ArrowRight aria-hidden="true" /></button>
  </div></main>
}
